### PR TITLE
Ensuring /usr/libexec/mcollective dir exist before using it

### PR DESCRIPTION
**Pull request by rameshmimit**

### CODE REVIEW

**Comment by igalic** [comment]
i might have just "solved" this by merging #211
@richardc: ping

**Comment by richardc** [comment]
Well #211 and 109a1cd are two different approaches to the same problem.

The other two commits in the PR are probably the less ambitious version of a revert of #157

**Comment by jyaworski** [comment]
Hello:

Can this be rebased and squashed? Is it still needed?

**Comment by jyaworski** [comment]
This looks like it was fixed. Please re-open if it isn't.

**Pull request closed without merging**
