### PR TITLE
Enabled SSL Ciphers configuration

### PR DESCRIPTION
**Pull request by mvisonneau**
Updated PR in favor of #263

### CODE REVIEW

**Comment by igalic** [comment]
@mvisonneau this will need an update to spec tests
```
 1) mcollective::user #middleware_ssl true and "true" should contain File[/home/nagios/.mcollective.d/credentials/private_keys/nagios.pem]
     Failure/Error: it { should contain_file('/home/nagios/.mcollective.d/credentials/private_keys/nagios.pem') }

     Puppet::PreformattedError:
       Evaluation Error: Unknown variable: 'ssl_ciphers'. at /home/travis/build/voxpupuli/puppet-mcollective/spec/fixtures/modules/mcollective/manifests/user/connector.pp:35:17 on node testing-worker-linux-docker-ffd2aa7b-3373-linux-8.prod.travis-ci.org
```

**Comment by jyaworski** [comment]
@mvisonneau tests still fail. It looks like the cron function behaves weirdly on Puppet 4.0. @igalic thoughts?

**Comment by igalic** [comment]
@jyaworski they're related to an update of the fqdn_rand() seed in puppet 4: https://docs.puppetlabs.com/puppet/4.4/reference/release_notes.html#puppet-440 / https://tickets.puppetlabs.com/browse/PUP-5646

**Comment by jyaworski** [comment]
@mvisonneau can you rebase?

**Comment by mvisonneau** [comment]
Thanks @igalic @jyaworski, I rebased, tests are fine now :)

**Pull request merged**
