### PR TITLE
Fixing PR #173

### PR DESCRIPTION
**Pull request by jhg03a**
This is a rebase+split for PR #173.

**Updates:**
1. The fixes for MODULES-1253 & MODULES-1255 are no longer relevant as the code is significantly different now.
2.  The fix for MODULES-1252 is better solved in PR #205, but included here for completeness.
3.  The fix for MODULES-1250 is fixed here and should supersede, PR #87, #97, & #98.

Due to time constraints, I'm unable to invest time in learning how to write tests for this PR.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello:

Is this in a good state to merge? It looks like rubocop is failing. If you want to cap rubocop at '0.35.0' for us, please add it to the Gemfile. Otherwise, the rubocop failure isn't your fault.

Please comment on the PRs referenced, and I'll close them once this is merged.

**Comment by jhg03a** [comment]
The MODULES-1250 fix addresses the problem where trying to override named settings that were hardcoded in the module itself would produce a duplicate resource error during catalog compilation.  It also addresses a problem where the order parameter was completely ignored and everything just got a priority of 50.

The MODULES-1252 fix is a step forward on fixing the client config in the case where you're using an SSL connection to your activemq middleware and the settings for the cert and key were missing.  I reference PR #205 because it is a more complete fix that addresses RabbitMQ as well.

**Comment by jhg03a** [comment]
Now that I've capped the Rubocop version, it still is failing because the spec uses rubocop features that didn't exist in '0.35.0'.  I can do a reverse commit if you like.

**Comment by jyaworski** [comment]
No problem. I'll just merge it. Thanks for the contribution.

**Pull request merged**
