### PR TITLE
Adding a sshkey security provider

### PR DESCRIPTION
**Pull request by DavidS**
This is a rebase and manual merge of @jhg03a's work. This closes #282

### CODE REVIEW

**Comment by bastelfreak** [comment]
thank you so much for the yak shaving @DavidS! Could you please take a look at the wrong scope access?

**Comment by DavidS** [comment]
ugh. thanks for noticing. @jhg03a needs to review this in-depth, that I haven't missed anything else.

**Comment by jyaworski** [comment]
I'm fine with merging this as-is and testing. @bastelfreak?

**Comment by bastelfreak** [comment]
I'm not familiar with the module. I would be happy if somebody who uses this makes a review or we wait for @jhg03a.

**Comment by DavidS** [comment]
@jyaworski this was a pretty hairy rebase/merge of @jhg03a's work, which apparently missed some. I'd really love to have Jonathan have a final :+1: before merging it.

But then, this is not my module, so proceed at will.

**Comment by igalic** [comment]
@DavidS at first sight this looks really good. I'll provide an indepth review tomorrow or monday.
i have one comment only so far: i am shocked — SHOCKED! — that you, of all people, didn't write tests for this 😜

**Comment by DavidS** [comment]
@igalic as you might notice, I only did the rebasing of @jhg03a's code. I
claim responsibility for everything that git has done wrong, but I don't
think I lost wholesale files.

**Comment by jyaworski** [comment]
@DavidS this needs a rebase now.

**Comment by jhg03a** [comment]
@DavidS The yak shaving looks good.

**Comment by jyaworski** [comment]
@DavidS please rebase.

**Pull request merged**
