### PR TITLE
SSL in common and feature to manage client keys

### PR DESCRIPTION
**Pull request by CMartinUdden**
New rebase and now passes tests at least.

### CODE REVIEW

**Comment by abraham1901** [comment]
:+1:
Thank you @CMartinUdden! You patch fix many errors in code and docs.

**Comment by ffrank** [comment]
So this replaces #204 I assume.

**Comment by igalic** [comment]
\*incoherent sobbing\*

**Comment by nibalizer** [comment]
@igalic here: 
candy-candy-30424649-1920-1200

**Comment by igalic** [comment]
you know what's real fun?
trying to rebase a 5 month old patch :s
it's so much fun, that i went and literally did everything else instead

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">i took a detour from rebasing a 5 month old pull request to learn some emacs and do my javascript &quot;homework&quot;</p>&mdash; The Wrath of me™ (@hirojin) <a href="https://twitter.com/hirojin/status/646777450572083204">September 23, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

i'll try again tomorrow…

**Comment by jyaworski** [comment]
This looks like it was fixed. Please re-open if it isn't.

**Pull request closed without merging**
