### PR TITLE
Allow puppetlabs-concat 2.x

### PR DESCRIPTION
**Pull request by roman-mueller**
Allow puppetlabs-concat 2.x

### CODE REVIEW

**Comment by igalic** [comment]
@roman-mueller can you also bump the version in .fixture.yml?
i'ld like to see what effect that has, and if we need to fix any warnings

**Comment by roman-mueller** [comment]
@igalic actually I was searching through the code just now and I cannot really find why this module needs the dependency on concat.
I think the dependency should be dropped, or am I missing something?

**Comment by igalic** [comment]
that's even better :D

**Comment by jyaworski** [comment]
I concur; it's only in fixtures and metadata.json. We should just remove it.

**Comment by roman-mueller** [comment]
Will create a new pull request for that in a minute.

**Pull request closed without merging**
