### PR TITLE
make the rpcaudit.logfile configurable

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by tampakrap** [comment]
are those test failures due to my changes?

**Comment by alexjfisher** [comment]
> are those test failures due to my changes?

Looks like you need to rebase to get some fixes that are already in master.

**Comment by alexjfisher** [comment]
@tampakrap Thanks for your PR!

Any chance of an extra spec test along the lines of https://github.com/voxpupuli/puppet-mcollective/blob/master/spec/classes/mcollective_spec.rb#L639 ?

**Comment by tampakrap** [comment]
@alexjfisher done. thanks for the review

**Comment by alexjfisher** [comment]
@tampakrap Great!  Thanks for adding the test.  Merged.

**Pull request merged**
