### PR TITLE
Enabled SSL Ciphers configuration

### PR DESCRIPTION
**Pull request by mvisonneau**
I've added the possibility to configure the ssl ciphers. I've encountered an issue while upgrading from 3.8.4 to 4.x

```
error 2015/11/19 10:30:03: rabbitmq.rb:45:in `on_ssl_connectfail' SSL session creation with stomp+ssl://mcollective@puppet.example.lan:61614 failed: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
````

Had to fix it with :

`mcollective::ssl_ciphers: AES256-SHA256`

### CODE REVIEW

**Comment by igalic** [comment]
Any chance you can fix the strict issues on puppet 4?

**Comment by mvisonneau** [comment]
I didn't get what the issue was on Puppet 4 tests, can you guide me though it ?

**Comment by igalic** [comment]
seems to be not caused by your commit. i'll look into it when I'm on a not phone.

**Comment by mvisonneau** [comment]
Any update onto this request ?

**Comment by jyaworski** [comment]
Checks are failing. Can you fix those/rebase/squash?

**Comment by jyaworski** [comment]
Please rebase.

**Comment by mvisonneau** [comment]
Closed in favor of #290

**Pull request closed without merging**
